In [1]:
"""This is a demo notebook how to use the CY_orientifolds and F_Theory_uplift class as an extension of CYTools. 
Many practical functions can be found in the Uplift_functions.py document whereas the two classes itself are in the FT_with_CY_orientifold.py file
"""

'This is a demo notebook how to use the CY_orientifolds and F_Theory_uplift class as an extension of CYTools. \nMany practical functions can be found in the Uplift_functions.py document whereas the two classes itself are in the FT_with_CY_orientifold.py file\n'

In [3]:
from cytools import fetch_polytopes, Polytope, vector_config, Cone, h_polytope
import numpy as np
import Uplift_functions as UF
import FT_with_CY_orientifold as FT

In [4]:
#Example: Orientifold and F-Theory uplift of P[1,1,1,1,4]
#Step 1: Define the polytope
p=Polytope([[-1,0,0,0],[1,1,0,0],[1,0,1,0],[1,0,0,1],[1,-1,-1,-1]])
#alternatively one can use
p=Polytope(UF.points_from_glsm([[1,1,1,1,4]]))
#P[1,1,1,1,4] is a trilayer model, so we can represent it in trilayer normal form
p=UF.trilayer_normal_form(p)

In [5]:
#To define an orientifold, we need to define the vector xi. For trilayer models, this can be found automatically and an orientifold object can be defined as
O11114_trilayer=FT.CY_orientifold(p)
#Alternatively, all inequivaleny orientifold options are found as
Z2_actions=UF.inequivalent_Z2_actions(p.automorphisms(action="left"))
print(Z2_actions)

[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 1]
 [1 1 0 0]]


In [6]:
#The CY_orientifold class can take multiple objects as inputs
from cytools.vector_config import VectorConfiguration
#A list of points and xi
#A polytope, from which all nonzero points will be used to define the orientifold, and xi
#A triangulation, in which case this triangulation will be used in general
#A VectorConfiguration
O_VC=FT.CY_orientifold(VectorConfiguration(p.points_not_interior_to_facets()[1:]),Z2_actions[1])
O_VC=FT.CY_orientifold(VectorConfiguration(p.points_not_interior_to_facets()[1:]).triangulate(),Z2_actions[1])

In [7]:
#When initializing a CY_orientifold object a triangulation, A1-singularities will be resolved when setting resolve_A1_singularities=True
from FT_with_CY_orientifold import CY_orientifold
#The maximal refined normal fan is constructed when setting make_Cartier_and_nef=True
#A triangulation is only then constructed, unless initially specified, if trianuglate_points=True is set
O_tri=CY_orientifold(p,make_Cartier_and_nef=True,triangulate_points=True)

In [8]:
#A few capabilities of the orientifold class
#Representation of D_B
print(O_tri.line_bundle())
#Ambient toric fan
print(O_tri.orbifold_toric_fan())
#All points of the ambient space
print(O_tri.points_orbifold())
#Normal fan
print(O_tri.normal_fan())

[1 0 0 0 0 0]
A fine triangulation of a 4-dimensional vector configuration consisting of #6 vectors
[[-1  0  0  0]
 [ 2 -1 -1 -3]
 [ 2  0  1  1]
 [ 2  1  0  1]
 [ 2  0  0  1]
 [ 1  0  0  0]]
A fine triangulation of a 4-dimensional vector configuration consisting of #5 vectors


In [9]:
#An F-Theory uplift object takes the same data as initializing an orientifold object. Of course, an orientifold object is initialized first
F=FT.F_Theory_Uplift(O_tri)
#Is nef partition?
print(F.is_nef_partition())
#Blowups
print(F.blowups())
#Various polytopes of both sides of the nef partition
print(F.pol_B_M(),F.pol_W_M(),F.pol_M_sum(),F.pol_M_conv())
print(F.pol_B_N(),F.pol_W_N(),F.pol_N_sum(),F.pol_N_conv())
#Hodge numbers (takes a few seconds)
print(F.h11(),F.h31())

True
[array([[ 1,  0,  0,  0, -1,  0],
       [ 2,  0,  0,  0,  0,  1]])]
A 4-dimensional lattice polytope in ZZ^6  A 6-dimensional lattice polytope in ZZ^6  A 6-dimensional reflexive lattice polytope in ZZ^6  A 6-dimensional reflexive lattice polytope in ZZ^6 
A 1-dimensional lattice polytope in ZZ^6  A 6-dimensional lattice polytope in ZZ^6  A 6-dimensional reflexive lattice polytope in ZZ^6  A 6-dimensional reflexive lattice polytope in ZZ^6 
2 3878


In [ ]:
#Various toric fans of the ambient varieties
print(F.orbifold_toric_fan()) #Fan of tilde V_4
print(F.singular_uplift_toric_fan()) #Toric fan of the uplift without resolution of NHCs
print(F.smooth_uplift_toric_fan())#Toric fan of the uplift after resolution of NHCs

A fine triangulation of a 4-dimensional vector configuration consisting of #6 vectors
A fine triangulation of a 6-dimensional vector configuration consisting of #9 vectors
A fine triangulation of a 6-dimensional vector configuration consisting of #11 vectors


In [12]:
#Representation of all the line bundles
print(F.line_bundle_base_M(),F.line_bundle_weierstrass_M())
print(F.line_bundle_base_N(),F.line_bundle_weierstrass_N())

[0 0 0 ... 1 1 1] [1 1 1 ... 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0] [0 1 1 1 1 1 1 1 1 1 1]


In [13]:
#Intersection numbers of the ambient toric sixfold
print(F.intersection_numbers_smooth_uplift())

{(1, 2, 3, 4, 7, 8): 1.0, (1, 2, 3, 4, 7, 9): 0.3333333333, (1, 2, 3, 4, 8, 9): 0.5, (1, 2, 3, 5, 7, 8): 1.0, (1, 2, 3, 5, 7, 9): 0.3333333333, (1, 2, 3, 5, 8, 9): 0.5, (1, 2, 4, 5, 7, 8): 1.0, (1, 2, 4, 5, 7, 9): 0.3333333333, (1, 2, 4, 5, 8, 9): 0.5, (1, 3, 4, 5, 7, 8): 1.0, (1, 3, 4, 5, 7, 9): 0.3333333333, (1, 3, 4, 5, 8, 9): 0.5, (2, 3, 4, 6, 7, 9): 0.3333333333, (2, 3, 4, 6, 7, 11): 0.3333333333, (2, 3, 4, 6, 8, 9): 0.5, (2, 3, 4, 6, 8, 10): 1.0, (2, 3, 4, 6, 10, 11): 1.0, (2, 3, 4, 7, 8, 10): 1.0, (2, 3, 4, 7, 10, 11): 1.0, (2, 3, 5, 6, 7, 9): 0.3333333333, (2, 3, 5, 6, 7, 11): 0.3333333333, (2, 3, 5, 6, 8, 9): 0.5, (2, 3, 5, 6, 8, 10): 1.0, (2, 3, 5, 6, 10, 11): 1.0, (2, 3, 5, 7, 8, 10): 1.0, (2, 3, 5, 7, 10, 11): 1.0, (2, 4, 5, 6, 7, 9): 0.3333333333, (2, 4, 5, 6, 7, 11): 0.3333333333, (2, 4, 5, 6, 8, 9): 0.5, (2, 4, 5, 6, 8, 10): 1.0, (2, 4, 5, 6, 10, 11): 1.0, (2, 4, 5, 7, 8, 10): 1.0, (2, 4, 5, 7, 10, 11): 1.0, (3, 4, 5, 6, 7, 9): 0.3333333333, (3, 4, 5, 6, 7, 11): 0.333333